version: 2

models:
  - name: customer_xf
    description: A table that shows customer with nation denormalised.

    columns:
      - name: c_custkey
        description: This is a unique identifier for the customer
        tests:
          - unique
          - not_null

  - name: orders_xf
    columns:
      - name: o_orderpriority
        description: This is the priority of the order
        tests:
          - accepted_values:
              values: ['1-URGENT', '2-HIGH', '3-MEDIUM', '4-NOT SPECIFIED', '5-LOW']

  - name: high_priority_orders
    columns:
      - name: o_orderpriority
        description: This is the priority of the order
        tests:
          - accepted_values:
              values: ['1-URGENT']
